### ISSUE TITLE
Error building with 2.3.1

### ISSUE THREAD

**Issue by jasonfma** [bitrise-io/steps-xcode-archive#80]
Not sure what other information I need to provide here. Please let me know.

```
+------------------------------------------------------------------------------+

| (6) xcode-archive                                                            |
+------------------------------------------------------------------------------+
| id: xcode-archive                                                            |
| version: 2.3.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-09-25T10:37:32-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[10:37:32]  * [OK] Step dependency (xcode) installed, available. 
INFO[10:37:32]  * [OK] Step dependency (go) installed, available. 
ipa export configs:
- ExportMethod: auto-detect
- UploadBitcode: yes
- CompileBitcode: yes
- TeamID: 
- UseDeprecatedExport: no
- CustomExportOptionsPlistContent:
xcodebuild configs:
- OutputTool: xcpretty
- Workdir: /Users/vagrant/git
- ProjectPath: /Users/vagrant/git/ios/Poe.xcodeproj
- Scheme: Poe
- Configuration: 
- OutputDir: /Users/vagrant/deploy
- IsCleanBuild: no
- XcodebuildOptions: -configuration Release
- ForceTeamID: 
- ForceProvisioningProfileSpecifier: 
- ForceProvisioningProfile: 
- ForceCodeSignIdentity: 
step output configs:
- IsExportXcarchiveZip: no
- ExportAllDsyms: yes
- ArtifactName: Poe
step determined configs:
- xcodebuildVersion: 9.0.0 (9A235)
- xcprettyVersion: 0.2.8

...

xcode major version > 9, generating exportOptions with provisioningProfiles node
Failed to create target code sign properties mapping, error: failed to run ruby script, output: {"error":"scheme does not contain buildable target\n/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/__ruby-script-runner__871297540/script.rb:219:in `read_code_sign_infos'\n/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/__ruby-script-runner__871297540/script.rb:275:in `<main>'"}, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive (exit code: 1)                                  | 235 sec  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-xcode-archive/issues      |
| Source: https://github.com/bitrise-io/steps-xcode-archive                    |
+---+---------------------------------------------------------------+----------+
```

**Comment by jasonfma** [comment]
Rolled back to 2.2.0 and there is no issue.

**Comment by sbehrends** [comment]
Having same issue.

Roll back didn't work, now im having other error "Failed to find matching provisioning profiles"

**Comment by godrei** [comment]
Hi @jasonfma and @sbehrends ,
thanks for the report, we are working on the fix. Until we release a new version please use this workaround: https://discuss.bitrise.io/t/xcode-9-gm-failed-to-create-target-code-sign-properties-mapping-error/2705/15?u=godreikrisztian

**Comment by trapacska** [comment]
Hi @jasonfma!

Just started to fix the issue, and we'll need more info to check what could be the issue in your case. Could you please contact us on our on-site chat and drop us your *.xcodeproj?

Thanks!

**Comment by sbehrends** [comment]
@trapacska I could help as well. Having same issue.

**Comment by godrei** [comment]
Hi, we released a new version of the step: [2.3.2](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.3.2).
Please update the step in your workflows and do not forget to update `Certificate and Profile Installer` step to the latest version ([1.9.0](https://github.com/bitrise-io/steps-certificate-and-profile-installer/releases/tag/1.9.0)) as well.
Let us know how does it work four you!

**Comment by jasonfma** [comment]
Looks like it works for me. Thanks!

**Comment by sbehrends** [comment]
Working as well. I think we can close the issue.

**Comment by trapacska** [comment]
Thanks for the report guys!

**Comment by kubajakowski** [comment]
@trapacska I've got same issue on 2.3.2 - after rolling back to 2.3.1 builds are passing as usual
